# site settings
title: "Guillermo Cano" # Your name and main role
subtitle: "Quality Engineering Manager" # A subtitle defining your focus and specialty
email: "guillecs86@gmail.com" # Your main contact email, from CV
description: >- # More specific description about your role and experience
  A digital portfolio showcasing my journey and expertise in Quality Engineering,
# baseurl: "" # THIS LINE HAS BEEN COMMENTED/REMOVED because the GitHub Pages workflow handles it automatically
url: "https://guillecs.github.io" # The base URL of your site. Make sure this is your GitHub Pages URL.

author:
  name: "Guillermo Cano" # Your full name as author

# homepage tiles
tiles-source: pages # Homepage tiles will look for pages
tiles-count: 4 # You currently have 4 tiles defined

# Definition of each tile for your portfolio
tiles:
  # Tile 1: About Me
  - title: "About Me: My Journey and Vision"
    subtitle: "My QE experience, leadership, and team management"
    image: assets/images/pic22.jpg # Ensure this image exists in assets/images/
    url: /about-me/ # The URL this tile will link to

  # Tile 2: Featured Projects (using your CV)
  - title: "Key acomplishments in Quality Engineering"
    subtitle: "Team management, QE Processes Implementation and strategies"
    image: assets/images/pic23.jpg # Ensure this image exists in assets/images/
    url: /acomplishments/ # The URL this tile will link to (Keeping /proyectos/ for now, consider if you want /projects/ for the actual collection)

  # Tile 3: My Posts and Articles
  - title: "My Posts and Articles"
    subtitle: "Analysis, insights, and guides on Quality Engineering"
    image: assets/images/pic20.jpg # Ensure this image exists in assets/images/
    url: /posts/ # The URL this tile will link to (Keeping /posts/ for now, consider if you want /articles/ for the actual collection)

  # Tile 4: My Curriculum Vitae
  - title: "My Curriculum Vitae"
    subtitle: "View my professional experience and skills"
    image: assets/images/pic21.jpg # Ensure this image exists in assets/images/
    url: /cv/ # The URL this tile will link to (Keeping /cv/ for now, consider if you want /resume/ for the actual collection)

# Custom collections (for your posts and projects)
collections:
  posts: # Configuration for your posts collection
    output: true # Ensures posts are generated as individual HTML pages
    permalink: /posts/:title/ # Defines the URL structure for your posts (e.g.: /posts/introduction-to-qe/)
  acomplishments: # Configuration for your projects collection
    output: true # This tells Jekyll to generate an HTML page for each individual project
    permalink: /acomplishments/:title/ # Defines the URL structure for each project (e.g.: /proyectos/my-first-project/)

# social settings (key must match Font Awesome icon name)
# See https://fontawesome.com/icons?d=gallery&s=brands
# Icons are not displayed if the value is empty
# You need to restart jekyll for changes to take effect
socials:
  GitHub: "https://github.com/guillecs" # Your GitHub profile
  LinkedIn: "https://www.linkedin.com/in/guillermo-cano-65778b40/" # Your LinkedIn profile (from CV)
  Email: "guillecs86@gmail.com" # A direct link to your contact email
  # You can add other social networks here if you wish, following the format:
  # Twitter: "https://twitter.com/yourusername"
  # Instagram: "https://www.instagram.com/yourusername"


# build settings
markdown: kramdown # Markdown processor used by Jekyll

sass:
  style: compressed # Compresses CSS for size optimization

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
